FROM node:alpine

WORKDIR /frontend
COPY package.json .
RUN yarn install
COPY . .

RUN apk --no-cache add gettext
RUN chmod +x ./docker-entrypoint-dev.sh
ENTRYPOINT ["./docker-entrypoint-dev.sh"]
CMD ["yarn", "start"]
