apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: d0rka/authentication-service-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*"
    - image: d0rka/authentication-service-backend-proxy
      context: backend-proxy
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*"
