name: Release Charts

on:
  push:
    branches:
      - main

# When you update this remember to touch Chart.yaml and values.yaml too
env:
  VERSION: 0.1.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend-proxy
          file: ./backend-proxy/Dockerfile
          push: true
          tags: |
            d0rka/authentication-service-backend-proxy:latest
            d0rka/authentication-service-backend-proxy:${{ github.sha }}
            d0rka/authentication-service-backend-proxy:${{ env.VERSION }}

      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            d0rka/authentication-service-frontend:latest
            d0rka/authentication-service-frontend:${{ github.sha }}
            d0rka/authentication-service-frontend:${{ env.VERSION }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: helm-charts
        env:
          CR_TOKEN: ${{ secrets.CR_TOKEN }}